---
title: "Regression Hazards"
output: html_notebook
---

This is to explore the effect of regressing out a 'confounder' like counts (nUMI) or percent mitochondrial genes.

Consider droplet data from the mammary gland.

```{r}
library(ggpubr)
```


```{r}
tissue_of_interest = "Mammary"
filename = here('00_data_ingest', '04_tissue_robj_generated', 
                      paste0("facs_", tissue_of_interest, "_seurat_tiss.Robj"))
load(file=filename)
```

Different cell types have very different means and variances.

```{r}
FetchData(tiss, c('nUMI', 'free_annotation')) %>% ggplot(aes(x = free_annotation, y = nUMI)) + geom_boxplot() + coord_flip()
ggsave(here("22_newfigs","MammaryUMIbyCellType.pdf"))
```

Mitochondrial genes, from [MitoCarta](https://www.broadinstitute.org/files/shared/metabolism/mitocarta/mouse.mitocarta.2.0.html).
```{r}
mito.genes = as.character(read_csv(here('22_newfigs','mitogenes.csv'))  %>% pull(Symbol))
mito.genes = mito.genes[mito.genes %in% rownames(tiss@raw.data)]
percent.mito = Matrix::colSums(tiss@raw.data[mito.genes, ])/Matrix::colSums(tiss@raw.data)

tiss <- AddMetaData(object = tiss, metadata = percent.mito, col.name = "percent.mito")

FetchData(tiss, c('percent.mito', 'free_annotation')) %>% ggplot(aes(x = free_annotation, y = percent.mito)) + geom_boxplot() + coord_flip()
ggsave(here("22_newfigs","MammaryPercentMitobyCellType.pdf"))
```

Kruskall-Wallis tests
```{r}
FetchData(tiss, c('percent.mito', 'free_annotation')) %>%  
  
kruskal.test(percent.mito ~ free_annotation, data = tiss@meta.data)

str(tiss@meta.data['free_annotation'])
```

```{r}
FetchData(tiss, c('percent.mito', 'Pecam1', 'free_annotation')) %>% ggplot(aes(x = percent.mito, y = Pecam1)) + geom_point() +
  geom_smooth(method = "lm", se = FALSE)

FetchData(tiss, c('percent.mito', 'Pecam1', 'free_annotation')) %>% ggplot(aes(x = percent.mito, y = Pecam1, color = free_annotation)) + geom_point() +
  geom_smooth(method = "lm", se = FALSE)

FetchData(tiss, c('percent.mito', 'Pecam1', 'free_annotation')) %>% filter(Pecam1 > 0) %>% ggplot(aes(x = percent.mito, y = Pecam1)) + geom_point() +  geom_smooth(method = "lm", se = FALSE)

FetchData(tiss, c('percent.mito', 'Pecam1', 'free_annotation')) %>% filter(Pecam1 > 0) %>% ggplot(aes(x = percent.mito, y = Pecam1, color = free_annotation)) + geom_point() +  geom_smooth(method = "lm", se = FALSE)
```


